apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services", "configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-services
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: service-reader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mb-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mb-controller
  template:
    metadata:
      labels:
        app: mb-controller
    spec:
      containers:
      - image: kong/blog:mocking-operator
        name: mb-controller
        imagePullPolicy: IfNotPresent
        env:
        - name: BASE_URL
          value: http://mountebank_my-services_svc_2525.mesh