apiVersion: v1
kind: Service
metadata:
  name: mountebank
  labels:
    app: mountebank
spec:
  ports:
  - name: http
    port: 2525
    targetPort: 2525
    appProtocol: http
  selector:
    app: mountebank
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mountebank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mountebank
  template:
    metadata:
      labels:
        app: mountebank
    spec:
      containers:
      - image: bbyars/mountebank:2.9.1
        name: mountebank
        ports:
        - containerPort: 2525