
apiVersion: v1
kind: Service
metadata:
  name: crew
  labels:
    app: crew
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    appProtocol: http
  selector:
    app: crew
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crew
  template:
    metadata:
      labels:
        app: crew
    spec:
      containers:
      - image: kong/blog:crew
        name: crew
        imagePullPolicy: IfNotPresent